### ISSUE TITLE
Incorrect selection behavior

### ISSUE THREAD

**Issue by robcecil** [nlampi/SwiftGridView#30]
Selection of cells inside of frozen rows or columns is wonky. 

Regardless of "allowsMultipleSelection" setting, I can tap non-frozen cells to select them, and select frozen cells, but unselecting selected frozen cells seem currently to not work.

I should be able to select both frozen and non-frozen cell, correct?

**Comment by nlampi** [comment]
Hi Rob, 
I have been testing out some situations and don't seem to be able to recreate the issue you mention.  Can you provide some more details about the setup/settings you have? Also, can you provide the version/iOS numbers?

**Comment by robcecil** [comment]
@nlampi working on it

**Comment by robcecil** [comment]
[ViewController.swift.zip](https://github.com/nlampi/SwiftGridView/files/1404318/ViewController.swift.zip)

**Comment by robcecil** [comment]
Here's a repro. Basically if you implement the protocol didSelectCellAtIndexPath and in your implementation call:

func dataGridView(_ dataGridView: SwiftGridView, cellAtIndexPath indexPath: IndexPath) 

to retrieve the actual cell, then the behavior is exhibited.

**Comment by nlampi** [comment]
@robcecil The issue is based on the call for dequeueing the cell. When called, the cell is being recreated rather than returning the existing cell. In the meantime while I investigate if anything can be done to resolve this, I have added some missing methods and properties to help with these issues. In your example, rather than dequeue the cell, you can get the existing cell using the below code.

`let cell = self.dataGridView.cellForItem(at: indexPath) as! BasicTextCell`

**Comment by robcecil** [comment]
Thanks @nlampi ... i think you are correct - probably a "bad practice" to call cellAtIndexPath to retrieve a cell since that method is used to create cells.

I wouldn't bend over backwards trying to work this out - I can easily code differently (like going to my underlying datasource to retrieve information about the cell).

Thanks
