### ISSUE TITLE
Memory issues with delegates.

### ISSUE THREAD

**Issue by sivakspt** [nlampi/SwiftGridView#6]
1.       In SwiftGridReusableView, the delegate var should be weak and the SwiftGridReusableViewDelegate class needs to be marked with the class keyword as other delegates are in order to be a weak var
2.       In SwiftGridLayout, the delegate is a lazy var. This seems like a strange choice by the library developer. I think it would be more standard to just have a weak var property that is set.

**Comment by nlampi** [comment]
I have pushed a new version 0.3.2 which fixes the first delegate issue as mentioned.
For the second issue, the property is lazy due to the fact that the collectionview is not available at init. Using lazy truly is the lazy way around this issue, but I have not been able to find a more efficient way to handle this yet. I will investigate it some more to see if there's a more elegant way.
